INSERT INTO instrument_types (code, name, description, category, display_order) VALUES ('EQ', 'Equity', 'Common stocks representing ownership in companies', 'EQUITY', 1);
INSERT INTO instrument_types (code, name, description, category, display_order) VALUES ('INDEX', 'Market Index', 'Statistical measures of stock market performance', 'INDEX', 3);
INSERT INTO instrument_types (code, name, description, category, display_order) VALUES ( 'CURR', 'Currency', 'Foreign exchange currency pairs for trading', 'CURRENCY', 6);
INSERT INTO instrument_types (code, name, description, category, display_order) VALUES ('OPT', 'Options', 'Contracts giving right to buy/sell assets at specific prices', 'DERIVATIVE', 11);
INSERT INTO instrument_types (code, name, description, category, display_order) VALUES ('BOND', 'Bonds', 'Fixed-income securities issued by corporations or governments', 'DEBT', 20);
INSERT INTO instrument_types (code, name, description, category, display_order) VALUES ('FUT', 'Futures', 'Standardized contracts to buy/sell assets at future dates', 'DERIVATIVE', 10);
INSERT INTO instrument_types (code, name, description, category, display_order) VALUES ( 'CRYPTO', 'Cryptocurrency', 'Digital or virtual currencies secured by cryptography', 'CRYPTO', 7);
INSERT INTO instrument_types (code, name, description, category, display_order) VALUES ( 'ETF', 'Exchange Traded Fund', 'Investment funds traded on stock exchanges like stocks', 'FUND', 2);
INSERT INTO instrument_types (code, name, description, category, display_order) VALUES ( 'COMM', 'Commodity', 'Physical goods like gold, silver, oil, agricultural products', 'COMMODITY', 51);
INSERT INTO instrument_types (code, name, description, category, display_order) VALUES ('PREF', 'Preference Shares', 'Preferred stocks with priority dividend rights', 'EQUITY', 5);
INSERT INTO instrument_types (code, name, description, category, display_order) VALUES ( 'MF', 'Mutual Fund', 'Pooled investment vehicles managed by professionals', 'FUND', 4);
INSERT INTO instrument_types (code, name, description, category, display_order) VALUES ( 'SIP', 'Systematic Investment Plan', 'Regular investment method in mutual funds', 'FUND', 41);
INSERT INTO instrument_types (code, name, description, category, display_order) VALUES ( 'PMS', 'Portfolio Management Service', 'Personalized investment management services', 'SERVICE', 63);
INSERT INTO instrument_types (code, name, description, category, display_order) VALUES ('WARR', 'Warrants', 'Securities giving right to purchase shares at specific prices', 'DERIVATIVE', 12);
INSERT INTO instrument_types (code, name, description, category, display_order) VALUES ('CD', 'Certificate of Deposit', 'Time deposits with fixed terms and interest rates', 'DEBT', 22);
INSERT INTO instrument_types (code, name, description, category, display_order) VALUES ('DEBEN', 'Debentures', 'Unsecured debt instruments backed by creditworthiness', 'DEBT', 21);
INSERT INTO instrument_types (code, name, description, category, display_order) VALUES ( 'AIF', 'Alternative Investment Fund', 'Privately pooled investment vehicles', 'FUND', 62);
INSERT INTO instrument_types (code, name, description, category, display_order) VALUES ( 'INVIT', 'Infrastructure Investment Trust', 'Trusts investing in infrastructure assets', 'TRUST', 61);
INSERT INTO instrument_types (code, name, description, category, display_order) VALUES ( 'REIT', 'Real Estate Investment Trust', 'Companies owning/operating income-producing real estate', 'TRUST', 60);
