"""int time changed to Time in Exchange

Revision ID: 0876d37b895d
Revises: b57f74f9b2cd
Create Date: 2025-12-01 00:10:57.359724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0876d37b895d'
down_revision: Union[str, Sequence[str], None] = 'b57f74f9b2cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchanges', 'pre_market_open_time',
               existing_type=sa.INTEGER(),
               type_=sa.Time(),
               existing_nullable=True)
    op.alter_column('exchanges', 'market_open_time',
               existing_type=sa.INTEGER(),
               type_=sa.Time(),
               existing_nullable=True)
    op.alter_column('exchanges', 'market_close_time',
               existing_type=sa.INTEGER(),
               type_=sa.Time(),
               existing_nullable=True)
    op.alter_column('exchanges', 'post_market_close_time',
               existing_type=sa.INTEGER(),
               type_=sa.Time(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchanges', 'post_market_close_time',
               existing_type=sa.Time(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('exchanges', 'market_close_time',
               existing_type=sa.Time(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('exchanges', 'market_open_time',
               existing_type=sa.Time(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('exchanges', 'pre_market_open_time',
               existing_type=sa.Time(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
