"""First Migration

Revision ID: 0f988ba75c34
Revises:
Create Date: 2025-11-18 13:17:35.685678

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0f988ba75c34"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchanges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("timezone", sa.String(length=128), nullable=True),
        sa.Column("country", sa.String(length=128), nullable=True),
        sa.Column("currency", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "instrument_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("category", sa.String(length=255), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "providers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("credentials", sa.JSON(), nullable=True),
        sa.Column("rate_limit", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sectors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "exchange_provider_mappings",
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("exchange_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["exchange_id"],
            ["exchanges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.PrimaryKeyConstraint(
            "provider_id", "exchange_id", name="pk_exchange_provider_mapping"
        ),
    )
    op.create_table(
        "instruments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("exchange_id", sa.Integer(), nullable=False),
        sa.Column("blacklisted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("delisted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("instrument_type_id", sa.Integer(), nullable=False),
        sa.Column("sector_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(
            ["exchange_id"],
            ["exchanges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_type_id"],
            ["instrument_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sector_id"],
            ["sectors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_instruments_exchange_id"), "instruments", ["exchange_id"], unique=False
    )
    op.create_index(
        op.f("ix_instruments_instrument_type_id"),
        "instruments",
        ["instrument_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_instruments_sector_id"), "instruments", ["sector_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("fname", sa.String(length=128), nullable=True),
        sa.Column("lname", sa.String(length=128), nullable=True),
        sa.Column("username", sa.String(length=128), nullable=True),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("profile_picture_url", sa.String(length=1024), nullable=True),
        sa.Column("blacklisted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_role_id"), "users", ["role_id"], unique=False)
    op.create_table(
        "price_history_daily",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("previous_close", sa.Float(), nullable=True),
        sa.Column("adj_close", sa.Float(), nullable=True),
        sa.Column("volume", sa.Integer(), nullable=True),
        sa.Column("deliver_percentage", sa.Float(), nullable=True),
        sa.Column(
            "price_not_found", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("dividend", sa.Float(), nullable=True),
        sa.Column("split", sa.Float(), nullable=True),
        sa.Column("split_adjusted", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_price_history_daily_instrument_id"),
        "price_history_daily",
        ["instrument_id"],
        unique=False,
    )
    op.create_table(
        "price_history_intraday",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("previous_close", sa.Float(), nullable=True),
        sa.Column("adj_close", sa.Float(), nullable=True),
        sa.Column("volume", sa.Integer(), nullable=True),
        sa.Column("deliver_percentage", sa.Float(), nullable=True),
        sa.Column(
            "price_not_found", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("interval", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_price_history_intraday_instrument_id"),
        "price_history_intraday",
        ["instrument_id"],
        unique=False,
    )
    op.create_table(
        "provider_instrument_mappings",
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column(
            "provider_instrument_search_code", sa.String(length=255), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.PrimaryKeyConstraint(
            "provider_id", "instrument_id", name="pk_provider_instrument_mapping"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("provider_instrument_mappings")
    op.drop_index(
        op.f("ix_price_history_intraday_instrument_id"),
        table_name="price_history_intraday",
    )
    op.drop_table("price_history_intraday")
    op.drop_index(
        op.f("ix_price_history_daily_instrument_id"), table_name="price_history_daily"
    )
    op.drop_table("price_history_daily")
    op.drop_index(op.f("ix_users_role_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_instruments_sector_id"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_instrument_type_id"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_exchange_id"), table_name="instruments")
    op.drop_table("instruments")
    op.drop_table("exchange_provider_mappings")
    op.drop_table("sectors")
    op.drop_table("roles")
    op.drop_table("providers")
    op.drop_table("instrument_types")
    op.drop_table("exchanges")
    # ### end Alembic commands ###
