"""watchlist exchange addition

Revision ID: 17feb4f2c72a
Revises: 2b42bf98a9d5
Create Date: 2026-01-15 23:20:52.855467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17feb4f2c72a'
down_revision: Union[str, Sequence[str], None] = '2b42bf98a9d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlists', sa.Column('exchange_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'watchlists', 'exchanges', ['exchange_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watchlists', type_='foreignkey')
    op.drop_column('watchlists', 'exchange_id')
    # ### end Alembic commands ###
