"""more tables for audit

Revision ID: 1fd583305dd5
Revises: 59a93dd12d61
Create Date: 2026-01-06 14:44:38.528665

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1fd583305dd5"
down_revision: Union[str, Sequence[str], None] = "59a93dd12d61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gate3_cycle_log",
        sa.Column("log_id", sa.UUID(), nullable=False),
        sa.Column("trade_id", sa.UUID(), nullable=False),
        sa.Column("instrument", sa.Text(), nullable=False),
        sa.Column("exchange", sa.Text(), nullable=False),
        sa.Column(
            "gate1_direction",
            postgresql.ENUM(name="gate1_direction_enum", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "gate2_status",
            postgresql.ENUM(name="gate2_status_enum", create_type=False),
            nullable=False,
        ),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column(
            "cycle_created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_service", sa.Text(), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("log_id"),
    )
    op.create_table(
        "gate3_decision_log",
        sa.Column("log_id", sa.UUID(), nullable=False),
        sa.Column("trade_id", sa.UUID(), nullable=False),
        sa.Column(
            "decision",
            postgresql.ENUM(name="gate3_decision_enum", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "decision_timestamp",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("architect_id", sa.Text(), nullable=False),
        sa.Column("auth_method", sa.Text(), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column("source_ip", postgresql.INET(), nullable=False),
        sa.PrimaryKeyConstraint("log_id"),
        sa.UniqueConstraint("trade_id"),
    )
    op.create_table(
        "gate3_execution_block_log",
        sa.Column("log_id", sa.UUID(), nullable=False),
        sa.Column("trade_id", sa.UUID(), nullable=False),
        sa.Column(
            "gate2_status",
            postgresql.ENUM(name="gate2_status_enum", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "gate3_decision",
            postgresql.ENUM(name="gate3_decision_enum", create_type=False),
            nullable=False,
        ),
        sa.Column("block_reason", sa.Text(), nullable=False),
        sa.Column(
            "timestamp",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("execution_service_id", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("log_id"),
    )
    op.create_table(
        "gate3_security_log",
        sa.Column("log_id", sa.UUID(), nullable=False),
        sa.Column(
            "timestamp",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("trade_id", sa.UUID(), nullable=True),
        sa.Column("attempted_action", sa.Text(), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=False),
        sa.Column("user_role", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Text(), nullable=True),
        sa.Column("source_ip", postgresql.INET(), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("log_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gate3_security_log")
    op.drop_table("gate3_execution_block_log")
    op.drop_table("gate3_decision_log")
    op.drop_table("gate3_cycle_log")
    # ### end Alembic commands ###
