"""Base Mixin Support in all

Revision ID: 25921eead67d
Revises: 0f988ba75c34
Create Date: 2025-11-19 21:47:37.635088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25921eead67d'
down_revision: Union[str, Sequence[str], None] = '0f988ba75c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_provider_mappings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('exchange_provider_mappings', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('exchanges', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('exchanges', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('exchanges', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('instrument_types', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('instrument_types', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('instrument_types', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('price_history_daily', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('price_history_daily', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('price_history_daily', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('price_history_intraday', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('price_history_intraday', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('price_history_intraday', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('provider_instrument_mappings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('provider_instrument_mappings', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('provider_instrument_mappings', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('providers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('providers', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('providers', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('roles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('roles', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('sectors', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('sectors', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('sectors', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('sectors', 'is_active')
    op.drop_column('sectors', 'updated_at')
    op.drop_column('sectors', 'created_at')
    op.drop_column('roles', 'is_active')
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    op.drop_column('providers', 'is_active')
    op.drop_column('providers', 'updated_at')
    op.drop_column('providers', 'created_at')
    op.drop_column('provider_instrument_mappings', 'is_active')
    op.drop_column('provider_instrument_mappings', 'updated_at')
    op.drop_column('provider_instrument_mappings', 'created_at')
    op.drop_column('price_history_intraday', 'is_active')
    op.drop_column('price_history_intraday', 'updated_at')
    op.drop_column('price_history_intraday', 'created_at')
    op.drop_column('price_history_daily', 'is_active')
    op.drop_column('price_history_daily', 'updated_at')
    op.drop_column('price_history_daily', 'created_at')
    op.drop_column('instrument_types', 'is_active')
    op.drop_column('instrument_types', 'updated_at')
    op.drop_column('instrument_types', 'created_at')
    op.drop_column('exchanges', 'is_active')
    op.drop_column('exchanges', 'updated_at')
    op.drop_column('exchanges', 'created_at')
    op.drop_column('exchange_provider_mappings', 'updated_at')
    op.drop_column('exchange_provider_mappings', 'created_at')
    # ### end Alembic commands ###
