"""show_on_watchlist added to watchlist 2

Revision ID: 2b42bf98a9d5
Revises: 80239b2e5dc4
Create Date: 2026-01-11 22:19:32.364419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b42bf98a9d5'
down_revision: Union[str, Sequence[str], None] = '80239b2e5dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlists', sa.Column('show_on_dashboard', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlists', 'show_on_dashboard')
    # ### end Alembic commands ###
