"""Resolve Tries Added

Revision ID: 3ea37a345e55
Revises: e7ae041a4e9c
Create Date: 2025-12-21 16:01:38.662270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ea37a345e55'
down_revision: Union[str, Sequence[str], None] = 'e7ae041a4e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_history_daily', sa.Column('resolve_tries', sa.Integer(), server_default='0', nullable=False))
    op.add_column('price_history_intraday', sa.Column('resolve_tries', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_history_intraday', 'resolve_tries')
    op.drop_column('price_history_daily', 'resolve_tries')
    # ### end Alembic commands ###
