"""Removing time values

Revision ID: 47dc884c150a
Revises: c068e3455e8a
Create Date: 2025-12-01 00:22:38.322914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47dc884c150a'
down_revision: Union[str, Sequence[str], None] = 'c068e3455e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchanges', 'post_market_close_time')
    op.drop_column('exchanges', 'market_open_time')
    op.drop_column('exchanges', 'pre_market_open_time')
    op.drop_column('exchanges', 'market_close_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchanges', sa.Column('market_close_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exchanges', sa.Column('pre_market_open_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exchanges', sa.Column('market_open_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exchanges', sa.Column('post_market_close_time', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
