"""new tables for audit

Revision ID: 59a93dd12d61
Revises: f077c8c6c750
Create Date: 2026-01-06 14:00:13.423314

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "59a93dd12d61"
down_revision: Union[str, Sequence[str], None] = "f077c8c6c750"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gate3_cycles",
        sa.Column("trade_id", sa.UUID(), nullable=False),
        sa.Column("instrument", sa.String(length=64), nullable=False),
        sa.Column("exchange", sa.String(length=32), nullable=False),
        sa.Column(
            "gate1_direction",
            postgresql.ENUM(name="gate1_direction_enum", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "gate2_status",
            postgresql.ENUM(name="gate2_status_enum", create_type=False),
            nullable=False,
        ),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column(
            "cycle_timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "gate3_decision",
            postgresql.ENUM(name="gate3_decision_enum", create_type=False),
            server_default="HOLD",
            nullable=False,
        ),
        sa.Column(
            "gate3_decision_timestamp", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("decision_reason", sa.String(length=160), nullable=True),
        sa.PrimaryKeyConstraint("trade_id"),
    )
    op.create_table(
        "gate3_logs",
        sa.Column("log_id", sa.UUID(), nullable=False),
        sa.Column("trade_id", sa.UUID(), nullable=False),
        sa.Column("log_type", sa.String(length=50), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("log_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gate3_logs")
    op.drop_table("gate3_cycles")
    # ### end Alembic commands ###
