"""change_status_to_int

Revision ID: 5e8d2c147244
Revises: 5844753f8336
Create Date: 2026-01-04 13:57:33.957086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e8d2c147244'
down_revision: Union[str, Sequence[str], None] = '5844753f8336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gate3_cycles')
    op.add_column('users', sa.Column('status', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.create_table('gate3_cycles',
    sa.Column('trade_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('instrument', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('exchange', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('gate1_direction', postgresql.ENUM('BUY', 'SELL', name='gate1_direction_enum'), autoincrement=False, nullable=False),
    sa.Column('gate2_status', postgresql.ENUM('SAFE', 'NOT_SAFE', name='gate2_status_enum'), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cycle_timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('gate3_decision', postgresql.ENUM('APPROVE', 'HOLD', 'BLOCK', name='gate3_decision_enum'), server_default=sa.text("'HOLD'::gate3_decision_enum"), autoincrement=False, nullable=False),
    sa.Column('gate3_decision_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('decision_reason', sa.VARCHAR(length=160), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('trade_id', name=op.f('gate3_cycles_pkey'))
    )
    # ### end Alembic commands ###
