"""NEW TIME VALUES

Revision ID: 5fecb169213f
Revises: 60a14f176dd0
Create Date: 2025-12-01 00:31:36.316588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fecb169213f'
down_revision: Union[str, Sequence[str], None] = '60a14f176dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchanges', sa.Column('pre_market_open_time', sa.Time(), nullable=True))
    op.add_column('exchanges', sa.Column('market_open_time', sa.Time(), nullable=False))
    op.add_column('exchanges', sa.Column('market_close_time', sa.Time(), nullable=False))
    op.add_column('exchanges', sa.Column('post_market_close_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchanges', 'post_market_close_time')
    op.drop_column('exchanges', 'market_close_time')
    op.drop_column('exchanges', 'market_open_time')
    op.drop_column('exchanges', 'pre_market_open_time')
    # ### end Alembic commands ###
