"""add_unique_constraints_to_price_history

Revision ID: 6405fb4efd4b
Revises: 3ea37a345e55
Create Date: 2025-12-21 16:57:59.213967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6405fb4efd4b'
down_revision: Union[str, Sequence[str], None] = '3ea37a345e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_price_history_daily_instrument_datetime', 'price_history_daily', ['instrument_id', 'datetime'])
    op.create_unique_constraint('uq_price_history_intraday_instrument_datetime', 'price_history_intraday', ['instrument_id', 'datetime'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_price_history_intraday_instrument_datetime', 'price_history_intraday', type_='unique')
    op.drop_constraint('uq_price_history_daily_instrument_datetime', 'price_history_daily', type_='unique')
    # ### end Alembic commands ###
