"""date to timestamp

Revision ID: 6b5586274681
Revises: 25921eead67d
Create Date: 2025-11-21 10:46:18.051821

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6b5586274681"
down_revision: Union[str, Sequence[str], None] = "25921eead67d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "price_history_daily",
        sa.Column("timestamp", postgresql.TIMESTAMP(), nullable=False),
    )
    op.drop_column("price_history_daily", "date")
    op.add_column(
        "price_history_intraday",
        sa.Column("timestamp", postgresql.TIMESTAMP(timezone=True), nullable=False),
    )
    op.drop_column("price_history_intraday", "date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "price_history_intraday",
        sa.Column(
            "date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("price_history_intraday", "timestamp")
    op.add_column(
        "price_history_daily",
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.drop_column("price_history_daily", "timestamp")
    # ### end Alembic commands ###
