"""date to timestamp(int)

Revision ID: 6c8d625055c0
Revises: 6b5586274681
Create Date: 2025-11-21 11:26:39.345289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c8d625055c0'
down_revision: Union[str, Sequence[str], None] = '6b5586274681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_history_daily', sa.Column('timestamp', sa.BigInteger(), nullable=False))
    op.drop_column('price_history_daily', 'date')
    op.add_column('price_history_intraday', sa.Column('timestamp', sa.BigInteger(), nullable=False))
    op.drop_column('price_history_intraday', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_history_intraday', sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('price_history_intraday', 'timestamp')
    op.add_column('price_history_daily', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('price_history_daily', 'timestamp')
    # ### end Alembic commands ###
