"""Exchange Timings Added

Revision ID: 7b780741160a
Revises: 6c8d625055c0
Create Date: 2025-11-24 09:21:11.332412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b780741160a'
down_revision: Union[str, Sequence[str], None] = '6c8d625055c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchanges', sa.Column('pre_market_open_time', sa.Integer(), nullable=True))
    op.add_column('exchanges', sa.Column('market_open_time', sa.Integer(), nullable=True))
    op.add_column('exchanges', sa.Column('market_close_time', sa.Integer(), nullable=True))
    op.add_column('exchanges', sa.Column('post_market_close_time', sa.Integer(), nullable=True))
    op.add_column('exchanges', sa.Column('is_open_24_hours', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchanges', 'is_open_24_hours')
    op.drop_column('exchanges', 'post_market_close_time')
    op.drop_column('exchanges', 'market_close_time')
    op.drop_column('exchanges', 'market_open_time')
    op.drop_column('exchanges', 'pre_market_open_time')
    # ### end Alembic commands ###
