"""show_on_watchlist added to watchlist

Revision ID: 80239b2e5dc4
Revises: ee7ce84a4e82
Create Date: 2026-01-11 22:18:07.382688

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "80239b2e5dc4"
down_revision: Union[str, Sequence[str], None] = "ee7ce84a4e82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "watchlists", sa.Column("show_on_dashboard", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("watchlists", "show_on_dashboard")
    # ### end Alembic commands ###
