"""NEW TIME VALUES 1

Revision ID: b33d3803d36e
Revises: 5fecb169213f
Create Date: 2025-12-01 00:32:53.999301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33d3803d36e'
down_revision: Union[str, Sequence[str], None] = '5fecb169213f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchanges', sa.Column('pre_market_open_time', sa.Time(), nullable=True))
    op.add_column('exchanges', sa.Column('market_open_time', sa.Time(), nullable=True))
    op.add_column('exchanges', sa.Column('market_close_time', sa.Time(), nullable=True))
    op.add_column('exchanges', sa.Column('post_market_close_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchanges', 'post_market_close_time')
    op.drop_column('exchanges', 'market_close_time')
    op.drop_column('exchanges', 'market_open_time')
    op.drop_column('exchanges', 'pre_market_open_time')
    # ### end Alembic commands ###
