"""back to Datetime

Revision ID: b57f74f9b2cd
Revises: f76d1ea87d96
Create Date: 2025-11-27 02:06:49.362875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b57f74f9b2cd'
down_revision: Union[str, Sequence[str], None] = 'f76d1ea87d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_history_daily', sa.Column('datetime', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('price_history_daily', 'timestamp')
    op.add_column('price_history_intraday', sa.Column('datetime', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('price_history_intraday', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_history_intraday', sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('price_history_intraday', 'datetime')
    op.add_column('price_history_daily', sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('price_history_daily', 'datetime')
    # ### end Alembic commands ###
