"""int time changed to Time in Exchange

Revision ID: c068e3455e8a
Revises: 0876d37b895d
Create Date: 2025-12-01 00:19:53.437759

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c068e3455e8a"
down_revision: Union[str, Sequence[str], None] = "0876d37b895d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "exchanges",
        "pre_market_open_time",
        existing_type=sa.INTEGER(),
        type_=sa.Time(),
        existing_nullable=True,
    )
    op.alter_column(
        "exchanges",
        "market_open_time",
        existing_type=sa.INTEGER(),
        type_=sa.Time(),
        nullable=False,
    )
    op.alter_column(
        "exchanges",
        "market_close_time",
        existing_type=sa.INTEGER(),
        type_=sa.Time(),
        nullable=False,
    )
    op.alter_column(
        "exchanges",
        "post_market_close_time",
        existing_type=sa.INTEGER(),
        type_=sa.Time(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "exchanges",
        "post_market_close_time",
        existing_type=sa.Time(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "exchanges",
        "market_close_time",
        existing_type=sa.Time(),
        type_=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "exchanges",
        "market_open_time",
        existing_type=sa.Time(),
        type_=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "exchanges",
        "pre_market_open_time",
        existing_type=sa.Time(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
