"""Changed price_not_found to resolve_required

Revision ID: e7ae041a4e9c
Revises: f8074233c2f6
Create Date: 2025-12-17 14:59:48.627834

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7ae041a4e9c"
down_revision: Union[str, Sequence[str], None] = "f8074233c2f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "price_history_daily",
        sa.Column(
            "resolve_required", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.drop_column("price_history_daily", "price_not_found")
    op.add_column(
        "price_history_intraday",
        sa.Column(
            "resolve_required", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.drop_column("price_history_intraday", "price_not_found")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "price_history_intraday",
        sa.Column(
            "price_not_found",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("price_history_intraday", "resolve_required")
    op.add_column(
        "price_history_daily",
        sa.Column(
            "price_not_found",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("price_history_daily", "resolve_required")
    # ### end Alembic commands ###
