"""added provider instrument segment

Revision ID: ee7ce84a4e82
Revises: 3326af5e626e
Create Date: 2026-01-08 23:47:35.923472

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ee7ce84a4e82"
down_revision: Union[str, Sequence[str], None] = "3326af5e626e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "provider_instrument_mappings",
        sa.Column("provider_instrument_segment", sa.String(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("provider_instrument_mappings", "provider_instrument_segment")
    # ### end Alembic commands ###
