"""fixing tables

Revision ID: f077c8c6c750
Revises: c4f7a909770e
Create Date: 2026-01-06 13:42:35.514296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f077c8c6c750'
down_revision: Union[str, Sequence[str], None] = 'c4f7a909770e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestion_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('suggestion_type_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['suggestion_type_id'], ['suggestion_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('gate3_cycles')
    op.drop_table('gate3_cycle_log')
    op.drop_table('execution_attempts')
    op.drop_table('gate3_execution_block_log')
    op.drop_table('gate3_decision_log')
    op.drop_table('gate3_security_log')
    op.add_column('users', sa.Column('status', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.create_table('gate3_security_log',
    sa.Column('log_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('trade_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('attempted_action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('failure_reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_role', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_ip', postgresql.INET(), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('log_id', name=op.f('gate3_security_log_pkey'))
    )
    op.create_table('gate3_decision_log',
    sa.Column('log_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('trade_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('decision', postgresql.ENUM('APPROVE', 'HOLD', 'BLOCK', name='gate3_decision_enum'), autoincrement=False, nullable=False),
    sa.Column('decision_timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('decision_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('architect_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('auth_method', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_ip', postgresql.INET(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('log_id', name=op.f('gate3_decision_log_pkey')),
    sa.UniqueConstraint('trade_id', name=op.f('gate3_decision_log_trade_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('gate3_execution_block_log',
    sa.Column('log_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('trade_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('gate2_status', postgresql.ENUM('SAFE', 'NOT_SAFE', name='gate2_status_enum'), autoincrement=False, nullable=False),
    sa.Column('gate3_decision', postgresql.ENUM('APPROVE', 'HOLD', 'BLOCK', name='gate3_decision_enum'), autoincrement=False, nullable=False),
    sa.Column('block_reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('execution_service_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('log_id', name=op.f('gate3_execution_block_log_pkey'))
    )
    op.create_table('execution_attempts',
    sa.Column('trade_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('attempt_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('result', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('trade_id', name=op.f('execution_attempts_pkey'))
    )
    op.create_table('gate3_cycle_log',
    sa.Column('log_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('trade_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('instrument', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('exchange', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('gate1_direction', postgresql.ENUM('BUY', 'SELL', name='gate1_direction_enum'), autoincrement=False, nullable=False),
    sa.Column('gate2_status', postgresql.ENUM('SAFE', 'NOT_SAFE', name='gate2_status_enum'), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cycle_created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('source_service', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('log_id', name=op.f('gate3_cycle_log_pkey'))
    )
    op.create_table('gate3_cycles',
    sa.Column('trade_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('instrument', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('exchange', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('gate1_direction', postgresql.ENUM('BUY', 'SELL', name='gate1_direction_enum'), autoincrement=False, nullable=False),
    sa.Column('gate2_status', postgresql.ENUM('SAFE', 'NOT_SAFE', name='gate2_status_enum'), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cycle_timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('gate3_decision', postgresql.ENUM('APPROVE', 'HOLD', 'BLOCK', name='gate3_decision_enum'), server_default=sa.text("'HOLD'::gate3_decision_enum"), autoincrement=False, nullable=False),
    sa.Column('gate3_decision_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('decision_reason', sa.VARCHAR(length=160), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('trade_id', name=op.f('gate3_cycles_pkey'))
    )
    op.drop_table('suggestions')
    op.drop_table('suggestion_types')
    # ### end Alembic commands ###
