"""Removed realtionship of instrument with pricehistories

Revision ID: f76d1ea87d96
Revises: 7b780741160a
Create Date: 2025-11-24 09:33:07.705812

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f76d1ea87d96"
down_revision: Union[str, Sequence[str], None] = "7b780741160a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
